# Generated by Django 6.1.2 on 2026-10-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=256)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('Ciudadano', 'Ciudadano'), ('Administrador', 'Administrador')], default='Ciudadano', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='ecoreporte_app.categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='ecoreporte_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ecoreporte_app.reporteambiental')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to='ecoreporte_app.usuario')),
            ],
        ),
    ]
